### ISSUE TITLE
Which syntax highlighting do I use?

### ISSUE THREAD

**Issue by nyteshade** [alpyre/language-amigaos-c#1]
When installed, I get six different line items and none of which seem to do the right thing. I only get any syntax highlighting when I choose C mode but then nothing Amiga related seems to popup. What am I doing wrong?

![screen shot 2017-03-07 at 11 21 53 pm](https://cloud.githubusercontent.com/assets/225558/23694134/fc20fbbe-038c-11e7-87c2-f183e82eb594.png)

**Comment by alpyre** [comment]
Thanks for the feedback.
 - Firstly there shouldn't be three `SDK-AmigaOS-Functions` and `SDK-AmigaOS-Symbols`. There should be only one of each!
That happens sometimes **when you make changes** in the **Highlight Settings** of the package. But luckily they go away after you **restart** Atom _(once again)_. Would you please do that and inform me the result _(if they don't disappear, then I'm in trouble)_. Thanks.

- Secondly you should always choose "**C mode**". Not the `SDK-AmigaOS-#?` ones. They are not complete grammars but just **"injecting grammars"** _(they inject AmigaOS API symbols to the C/C++ grammars)_.

- Thirdly auto-complete pop-ups are dependent on the **autocomplete-plus package v2.34 and above**.
_(I suppose I should have set that as package dependency. My bad)._
Would you please check your autocomplete-plus package version.

**Comment by alpyre** [comment]
Are you on Linux!?
I just found a bug of mine that would only occur on Linux machines.
If you are, please update your language-amigaos-c package and hopefully it will be fixed.

**Comment by alpyre** [comment]
Since there is no reply from you, I am assuming this as fixed. Thank you.

**Comment by nyteshade** [comment]
Apologies. Yes the ide simply needed restarting.
