### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by NILTONRAMOS** [alpyre/language-amigaos-c#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 14.04.5
**Thrown From**: [language-amigaos-c](https://github.com/alpyre/language-amigaos-c) package 1.1.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///opt/atom/resources/app.asar/static/index.html:2199

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at fs.readFile (/packages/language-amigaos-c/lib/autocomplete-provider.js:129:33)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

### Commands

```
     -9:55.6.0 core:paste (span.syntax--text.syntax--plain.syntax--null-grammar)
     -9:53.2.0 core:confirm (input.hidden-input)
     -9:20.1.0 core:paste (div.placeholder-text)
  2x -9:17.6.0 core:confirm (input.hidden-input)
 27x -4:04.9.0 core:backspace (input.hidden-input)
     -3:58 core:confirm (input.hidden-input)
     -0:18.3.0 core:paste (span.syntax--text.syntax--plain.syntax--null-grammar)
     -0:15.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
busy-signal 1.3.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.1 
gpp-compiler 3.0.7 
Hydrogen 1.7.0 
intentions 1.1.2 
language-amigaos-c 1.1.0 
linter 2.1.2 
linter-ui-default 1.2.1 
minimap 4.26.8 
minimap-linter 2.0.0 
nord-atom-syntax 0.6.0 
```

**Comment by alpyre** [comment]
Thanks for the feedback.
I could not reproduce this on Windows7(x64) Atom 1.15.0 and Ubuntu 14.04.5 Atom 1.16.0-dev.

Would you please try changing a highlight preference in language-amigaos-c package settings and restart Atom.

If the error persists would you please inform your highlight preferences. Thanks.

**Comment by alpyre** [comment]
After trying on 3 more different machines I finally could reproduce the issue. It seems it happens because of a racing condition between the package script creating the grammar files and Atom trying to read them (that should be the reason why it only occurs only on some systems).
I've changed the file creation step to be synchoronous now. Hopefully that will resolve this issue.
